/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Facturas;

import Controlador.ControladorArticulos;
import Controlador.ControladorFacturas;
import Modelo.Articulos;
import Modelo.FacturasCab;
import Modelo.FacturasLin;
import Modelo.FacturasLinId;
import Modelo.FacturasTot;
import Vista.Principal;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class vCrearLineasFactura extends javax.swing.JDialog {

    FacturasCab cabecera = vCrearFacturas.cabecera;
    BigDecimal base = new BigDecimal(0), descuento = new BigDecimal(0), iva = new BigDecimal(0), total = new BigDecimal(0);
    FacturasTot facturaTotal = new FacturasTot(cabecera, base, descuento, iva, total);

    List<FacturasLin> listaLineas = new ArrayList<>();
    List<Articulos> listaArticulosAModificar = new ArrayList<>();

    DefaultTableModel modeloCabecera, modeloLineas, modeloTotal;

    ControladorFacturas ctrl = new ControladorFacturas();
    ControladorArticulos ctrlA = new ControladorArticulos();

    /**
     * Creates new form vCrearLineasFactura
     */
    public vCrearLineasFactura(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        sCantidad.setValue(1);
        this.setLocationRelativeTo(null);
        modeloCabecera = (DefaultTableModel) tCabecera.getModel();
        modeloLineas = (DefaultTableModel) tLineas.getModel();
        modeloTotal = (DefaultTableModel) tTotal.getModel();
        rellenarArticulos();
        rellenarCabecera();
        rellenarTotal();
        rellenarLineas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tCabecera = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tLineas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tTotal = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cbArticulos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sCantidad = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        etDescuento = new javax.swing.JFormattedTextField();
        bCancelar = new javax.swing.JButton();
        bAgregar = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        bGenerarFactura = new javax.swing.JButton();

        jScrollPane4.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Generar Líneas de Factura");
        setResizable(false);

        tCabecera.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tCabecera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Fecha", "DNI/CIF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tCabecera.setEnabled(false);
        tCabecera.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tCabecera);
        if (tCabecera.getColumnModel().getColumnCount() > 0) {
            tCabecera.getColumnModel().getColumn(0).setResizable(false);
            tCabecera.getColumnModel().getColumn(1).setResizable(false);
            tCabecera.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setText("Factura Actual:");

        tLineas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Línea", "Referencia", "Cantidad", "Precio", "Descuento", "Iva"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tLineas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tLineas.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tLineas);
        if (tLineas.getColumnModel().getColumnCount() > 0) {
            tLineas.getColumnModel().getColumn(0).setResizable(false);
            tLineas.getColumnModel().getColumn(1).setResizable(false);
            tLineas.getColumnModel().getColumn(2).setResizable(false);
            tLineas.getColumnModel().getColumn(3).setResizable(false);
            tLineas.getColumnModel().getColumn(4).setResizable(false);
            tLineas.getColumnModel().getColumn(5).setResizable(false);
            tLineas.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel2.setText("Líneas de la factura:");

        tTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tTotal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Base", "Descuento", "Iva", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tTotal.setEnabled(false);
        tTotal.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tTotal);
        if (tTotal.getColumnModel().getColumnCount() > 0) {
            tTotal.getColumnModel().getColumn(0).setResizable(false);
            tTotal.getColumnModel().getColumn(1).setResizable(false);
            tTotal.getColumnModel().getColumn(2).setResizable(false);
            tTotal.getColumnModel().getColumn(3).setResizable(false);
            tTotal.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel3.setText("Total de la factura:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        cbArticulos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("Artículos:");

        jLabel5.setText("Cantidad:");

        sCantidad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sCantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sCantidadStateChanged(evt);
            }
        });

        jLabel6.setText("Descuento:");

        etDescuento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        etDescuento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        bCancelar.setText("Cancelar");
        bCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bAgregar.setText("Agregar");
        bAgregar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });

        bBorrar.setText("Borrar");
        bBorrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        bGenerarFactura.setText("Generar Factura");
        bGenerarFactura.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bGenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGenerarFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(etDescuento, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(sCantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(bBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(bAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addGap(61, 61, 61)
                                .addComponent(cbArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bGenerarFactura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(cbArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(sCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(etDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bCancelar)
                            .addComponent(bAgregar)
                            .addComponent(bBorrar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(bGenerarFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGenerarFacturaActionPerformed
        for (Articulos a : listaArticulosAModificar) {
            ctrlA.modificarArticulos(a);
        }
        cabecera.setFacturasLins((Set) listaLineas);
        cabecera.setFacturasTot(facturaTotal);
        ctrl.anadirCabecera(cabecera);
        JOptionPane.showMessageDialog(this, "Factura generada con éxito");
        dispose();
    }//GEN-LAST:event_bGenerarFacturaActionPerformed

    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        boolean repetido = false;
        if (!etDescuento.getText().isEmpty()) {
            Articulos a = (Articulos) cbArticulos.getSelectedItem();
            if (Double.parseDouble(a.getStock().toString()) >= Double.parseDouble(sCantidad.getValue().toString())) {
                for (FacturasLin l : listaLineas) {
                    if (a.getReferencia() == l.getArticulos().getReferencia()) {
                        repetido = true;
                    }
                }
                if (repetido) {
                    for (FacturasLin l : listaLineas) {
                        if (a.getReferencia() == l.getArticulos().getReferencia()) {
                            listaLineas.remove(l);
                            l.setCantidad(new BigDecimal(Integer.parseInt(l.getCantidad().toString()) + (Integer) sCantidad.getValue()));
                            listaLineas.add(l);
                            a.setStock(new BigDecimal(Double.parseDouble(a.getStock().toString()) - Double.parseDouble(sCantidad.getValue().toString())));
                            listaArticulosAModificar.add(a);
                            for (Articulos a1 : Principal.listaArticulos) {
                                if (a1.getReferencia() == a.getReferencia()) {
                                    Principal.listaArticulos.remove(a1);
                                    Principal.listaArticulos.add(a);
                                    break;
                                }
                            }
                        }
                    }
                } else {
                    FacturasLinId id = new FacturasLinId(cabecera.getNumfac(), ctrl.ultimoNumLinFac(cabecera));
                    FacturasLin linea = new FacturasLin(id, a, cabecera, new BigDecimal((Integer) sCantidad.getValue()), a.getPrecio(), new BigDecimal(etDescuento.getText()), a.getPorciva());
                    listaLineas.add(linea);
                    a.setStock(new BigDecimal(Double.parseDouble(a.getStock().toString()) - Double.parseDouble(sCantidad.getValue().toString())));
                    listaArticulosAModificar.add(a);
                    for (Articulos a1 : Principal.listaArticulos) {
                        if (a1.getReferencia() == a.getReferencia()) {
                            Principal.listaArticulos.remove(a1);
                            Principal.listaArticulos.add(a);
                            break;
                        }
                    }
                }
                rellenarLineas();
                calcularTotal();
            } else {
                getToolkit().beep();
                JOptionPane.showMessageDialog(this, "No hay sufiente stock de ese artículo, el stock es de " + a.getStock(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "No puede haber ningun campo vacío", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bAgregarActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        if (tLineas.getSelectedRow() != -1) {
            if (JOptionPane.showConfirmDialog(this, "¿Está seguro que desea borrar línea?", "Confirme la operación", JOptionPane.OK_CANCEL_OPTION) == 0) {
                FacturasLin linea = (FacturasLin) tLineas.getValueAt(tLineas.getSelectedRow(), 0);
                for (Articulos a1 : Principal.listaArticulos) {
                    if (a1.getReferencia() == linea.getArticulos().getReferencia()) {
                        Principal.listaArticulos.remove(a1);
                        a1.setStock(new BigDecimal(Double.parseDouble(a1.getStock().toString()) + Double.parseDouble(linea.getCantidad().toString())));
                        Principal.listaArticulos.add(a1);
                        break;
                    }
                }
                listaLineas.remove(linea);
                rellenarLineas();
                calcularTotal();
            }
        } else {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Selecciona una linea de factura para borrar", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bBorrarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        if (JOptionPane.showConfirmDialog(this, "¿Está seguro que desea cancelar la operación?", "Confirme", JOptionPane.OK_CANCEL_OPTION) == 0) {
            for (FacturasLin f : listaLineas) {
                for (Articulos a1 : Principal.listaArticulos) {
                    if (a1.getReferencia() == f.getArticulos().getReferencia()) {
                        Principal.listaArticulos.remove(a1);
                        a1.setStock(new BigDecimal(Double.parseDouble(a1.getStock().toString()) + Double.parseDouble(f.getCantidad().toString())));
                        Principal.listaArticulos.add(a1);
                        break;
                    }
                }
            }
            dispose();
        }
    }//GEN-LAST:event_bCancelarActionPerformed

    private void sCantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sCantidadStateChanged
        if ((Integer) sCantidad.getValue() < 1) {
            getToolkit().beep();
            sCantidad.setValue(1);
        }
    }//GEN-LAST:event_sCantidadStateChanged

    private void rellenarArticulos() {
        cbArticulos.removeAllItems();
        for (Articulos a : Principal.listaArticulos) {
            cbArticulos.addItem(a);
        }
    }

    private void rellenarCabecera() {
        modeloCabecera.setRowCount(0);
        SimpleDateFormat format =new SimpleDateFormat("dd/MM/yyyy");
        modeloCabecera.addRow(new Object[]{cabecera, format.format(cabecera.getFechafac()), cabecera.getClientes().getDnicif()});
    }

    private void rellenarLineas() {
        modeloLineas.setRowCount(0);
        for (FacturasLin f : listaLineas) {
            modeloLineas.addRow(new Object[]{f, f.getId().getLineafac(), f.getArticulos().getReferencia(), f.getCantidad(), f.getPrecio(), f.getDtolinea(), f.getIvalinea()});
        }
    }

    private void rellenarTotal() {
        modeloTotal.setRowCount(0);
        modeloTotal.addRow(new Object[]{facturaTotal.getFacturasCab().getNumfac(), facturaTotal.getBaseimp(), facturaTotal.getImpDto(), facturaTotal.getImpIva(), facturaTotal.getTotalfac()});
    }

    private void calcularTotal() {
        Double base = 0.0, descuentoTotal = 0.0, ivaTotal = 0.0;
        for (FacturasLin linea : listaLineas) {
            Double cantidad = Double.parseDouble(linea.getCantidad().toString());
            Double precio = Double.parseDouble(linea.getPrecio().toString());
            Double descuento = Double.parseDouble(linea.getDtolinea().toString());
            Double iva = Double.parseDouble(linea.getIvalinea().toString());
            base += cantidad * precio;
            descuentoTotal += cantidad * precio * (descuento / 100);
            ivaTotal += cantidad * precio * (descuento / 100) * (iva / 100);
        }
        Double total = base - descuentoTotal;
        facturaTotal = new FacturasTot(cabecera, new BigDecimal(base), new BigDecimal(descuentoTotal), new BigDecimal(ivaTotal), new BigDecimal(total));
        rellenarTotal();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vCrearLineasFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vCrearLineasFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vCrearLineasFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vCrearLineasFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vCrearLineasFactura dialog = new vCrearLineasFactura(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bGenerarFactura;
    private javax.swing.JComboBox<Articulos> cbArticulos;
    private javax.swing.JFormattedTextField etDescuento;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner sCantidad;
    private javax.swing.JTable tCabecera;
    private javax.swing.JTable tLineas;
    private javax.swing.JTable tTotal;
    // End of variables declaration//GEN-END:variables
}
