/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Ofertas;

import Controlador.ControladorFacturas;
import Modelo.FacturasCab;
import Vista.Principal;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class vOfertas extends javax.swing.JDialog {

    ControladorFacturas ctrl = new ControladorFacturas();
    DefaultTableModel modelo;

    /**
     * Creates new form vOfertas
     */
    public vOfertas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        modelo = (DefaultTableModel) tOfertas.getModel();
        rellenarTabla(Principal.listaFacturas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tOfertas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        etFiltroOfertas = new javax.swing.JTextField();
        cbFiltroOfertas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        bCrear = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        bBorrar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        bUtilizarOferta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Ofertas");

        tOfertas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tOfertas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tOfertas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tOfertas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tOfertas);
        if (tOfertas.getColumnModel().getColumnCount() > 0) {
            tOfertas.getColumnModel().getColumn(0).setResizable(false);
            tOfertas.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("OFERTAS");

        etFiltroOfertas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                etFiltroOfertasFocusGained(evt);
            }
        });
        etFiltroOfertas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etFiltroOfertasKeyTyped(evt);
            }
        });

        cbFiltroOfertas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Número", "Cliente" }));
        cbFiltroOfertas.setToolTipText("");
        cbFiltroOfertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFiltroOfertasActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Filtro : ");

        jToolBar1.setFloatable(false);

        bCrear.setText("Crear");
        bCrear.setFocusable(false);
        bCrear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCrear.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearActionPerformed(evt);
            }
        });
        jToolBar1.add(bCrear);
        jToolBar1.add(jSeparator1);

        bBorrar.setText("Borrar");
        bBorrar.setFocusable(false);
        bBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bBorrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });
        jToolBar1.add(bBorrar);
        jToolBar1.add(jSeparator2);

        bUtilizarOferta.setText("Utilizar Oferta");
        bUtilizarOferta.setFocusable(false);
        bUtilizarOferta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bUtilizarOferta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bUtilizarOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUtilizarOfertaActionPerformed(evt);
            }
        });
        jToolBar1.add(bUtilizarOferta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(etFiltroOfertas, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbFiltroOfertas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etFiltroOfertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFiltroOfertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void etFiltroOfertasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_etFiltroOfertasFocusGained
        if (etFiltroOfertas.getText().isEmpty()) {
            rellenarTabla(Principal.listaOfertas);
        } else {
            rellenarTabla(ctrl.filtrarFacturas(Principal.listaOfertas, cbFiltroOfertas.getSelectedIndex(), etFiltroOfertas.getText()));
        }
    }//GEN-LAST:event_etFiltroOfertasFocusGained

    private void etFiltroOfertasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etFiltroOfertasKeyTyped
        cbFiltroOfertas.requestFocus();
        etFiltroOfertas.requestFocus();
    }//GEN-LAST:event_etFiltroOfertasKeyTyped

    private void cbFiltroOfertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFiltroOfertasActionPerformed
        if (!etFiltroOfertas.getText().isEmpty()) {
            rellenarTabla(ctrl.filtrarFacturas(Principal.listaOfertas, cbFiltroOfertas.getSelectedIndex(), etFiltroOfertas.getText()));
        }
    }//GEN-LAST:event_cbFiltroOfertasActionPerformed

    private void bCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearActionPerformed
        vCrearOfertas v = new vCrearOfertas(null, true);
        this.setVisible(false);
        v.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_bCrearActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        if (tOfertas.getSelectedRow() != -1) {
            FacturasCab cab = (FacturasCab) tOfertas.getValueAt(tOfertas.getSelectedRow(), 0);
            Principal.listaOfertas.remove(cab);
            String json = ctrl.generarJSONOfertas(Principal.listaOfertas);
            try {
                FileWriter f1 = new FileWriter("Ofertas.json");
                f1.write(json);
                f1.flush();
                f1.close();
            } catch (IOException ex) {
                System.out.println("Error : " + ex.getMessage());
            }
            JOptionPane.showMessageDialog(this, "Nuevo json generado (en la raiz del jar)");
        } else {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Seleccione una oferta para borrar");
        }
    }//GEN-LAST:event_bBorrarActionPerformed

    private void bUtilizarOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUtilizarOfertaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bUtilizarOfertaActionPerformed

    private void rellenarTabla(List<FacturasCab> lista) {
        modelo.setRowCount(0);
        for (FacturasCab a : lista) {
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            modelo.addRow(new Object[]{a, format.format(a.getFechafac())});
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vOfertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vOfertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vOfertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vOfertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vOfertas dialog = new vOfertas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bCrear;
    private javax.swing.JButton bUtilizarOferta;
    private javax.swing.JComboBox<String> cbFiltroOfertas;
    private javax.swing.JTextField etFiltroOfertas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tOfertas;
    // End of variables declaration//GEN-END:variables
}
